### PR TITLE
Fix hit test devicePixelRatio bug

### LINKED ISSUE #49: Hit tests wrong location for devicePixelRatio values other than 2
Hit testing takes pixel coordinates and uses them to compute which sprites intersect or are inside a region of interest. Currently, this works with `devicePixelRatio` equal to 2. When the value is greater than 2, then the region is incorrectly specified to me smaller and nearer the top-left (canvas origin). When the value is less than 2, the region is incorrectly specified to be larger and further from the top-left.

### PR DESCRIPTION
**Pull request by jimbojw**
Fixes:

* Tests are now immune to WebGL context loss due to too many contexts. #48
* `hitTest()` now works for `devicePixelRatio` other than 2. #49
* Fixes previously undisclosed bug in border radius computation for `devicePixelRatio` other than 2.
* Implements unit tests for Scene `hitTest()` method.

### CODE REVIEW

File: src/lib/shaders/scene-vertex-shader.ts [hunk 1]
```diff
@@ -297,15 +302,20 @@ void main () {
...
+  float currentBorderPlacement = borderProperties.z;
 
   // The fragment shader needs to know the threshold signed distances that
   // indicate whether each pixel is inside the shape, in the boreder, or outside
   // of the shape.
   vec2 projectedSizePixel = computedSize.xy * viewMatrixScale.xy;
-  float edgeDistance = borderProperties.x +
-    borderProperties.y * 8. / min(projectedSizePixel.x, projectedSizePixel.y);
+  float edgeDistance = currentBorderRadiusWorld + (
+      currentBorderRadiusPixel * 4. * devicePixelRatio /
```
Comment (RyanMullins) [inline src/lib/shaders/scene-vertex-shader.ts]: The multiplication by 4 here seems like a bit of a magic number to me. Worth documenting?

**Review by RyanMullins — APPROVED** [review]

File: src/lib/shaders/scene-vertex-shader.ts (hunk 1 above)
Comment (jimbojw) [reply src/lib/shaders/scene-vertex-shader.ts]: Thanks for the review. It's definitely a magic number. Let me see if I can figure out what it means.

**Review by GradySimon — APPROVED** [review]

File: src/lib/shaders/scene-vertex-shader.ts (hunk 1 above)
Comment (jimbojw) [reply src/lib/shaders/scene-vertex-shader.ts]: Explanation added, PTAL.

Comment (RyanMullins) [reply src/lib/shaders/scene-vertex-shader.ts]: Thanks, those two constants make the whole computation a lot more obvious!

Comment (jimbojw) [reply src/lib/shaders/scene-vertex-shader.ts]: No worries. Thanks for bringing these issues up. There was a lot of development in the beginning wherein I was focused on making it look right (the rendered output, not the code). Some of these magic values are holdovers from that time.
