### PR TITLE
`devicePixelRatio`: fix rendering, `resize()` logic, expose setting and add tests

### LINKED ISSUE #44: Support `devicePixelRatio` values other than 2, provide config option and tests
Currently, Megaplot only works with `devicePixelRatio` equal to 2. When `devicePixelRatio` is any other number, sprites render in the wrong position and size. Specifically, for `devicePixelRatio` equal to 1, sprites are twice as big as intended.

Cause: In `SceneInternal`, the `getViewMatrix()` and `getViewScale()` methods both use a hard-coded scale factor of 4. Instead, the scale factor should be 2 times the `devicePixelRatio`.

In order to test this change, determining the `devicePixelRatio` should be made into an optional, configurable function which the creator of the `Scene` may provide, like the current `timingFunctions` option. Then, whenever Megaplot needs the `devicePixelRatio`, it will consult ether the API-user provided function, or the default function which reads from `window.devicePixelRatio` if present or defaults to 1.

### PR DESCRIPTION
**Pull request by jimbojw**
Fixes #44:

- Bug fix: use `devicePixelRatio` when computing viewMatrix and viewScale uniforms for vertex shader.
- Expose an optional Scene constructor setting for making `devicePixelRatio` a specific number or a callback function which will be invoked to determine the `devicePixelRatio` on resize.
- Update `resize()` logic to incorporate changes to `devicePixelRatio`.
- Add `devicePixelRatio` setting in the debugging demo for manual testing.
- Add karma unit tests for `devicePixelRatio` values of 0.5, 1, 2 and 3, and dynamically changing between 2 and 1.

### CODE REVIEW

File: src/lib/scene-internal.ts [hunk 1]
```diff
@@ -839,18 +870,23 @@ export class SceneInternal implements Renderer {
    * View matrix converts world units into view (pixel) coordinates.
    */
   getViewMatrix() {
+    if (!this.lastDevicePixelRatio) {
+      throw new InternalError('initView must set lastDevicePixelRatio');
+    }
+
+    const scaleFactor = 2 * this.lastDevicePixelRatio;
```
Comment (RyanMullins) [inline src/lib/scene-internal.ts]: Might be worth commenting that this scale. factor is 2x the DPR because we're dealing with a display window of [-1, 1] instead of [0, 1].

File: test/scene-integration.test.ts [hunk 2]
```diff
@@ -365,5 +365,575 @@ describe('Scene', () => {
...
+      );
+      expect(compareColorArrays(centerSample.data, magentaPatch)).toEqual(1);
+    });
+  });
+
+  describe('devicePixelRatio', () => {
+    const section = createSection('Scene::devicePixelRatio');
+    const sectionContent = section.querySelector('.content')!;
+
+    it('should render normally at devicePixelRatio=0.5', async () => {
```
Comment (RyanMullins) [inline test/scene-integration.test.ts]: This seems like a prime use case for parameterized tests. There's a [jasmine-parameterized](https://www.npmjs.com/package/jasmine-parameterized) package similar to `absl.testing.parameterized`, or you can [do it manually](https://medium.com/@nyablk97/parameterized-tests-with-jasmine-ecadb2856980)

**Review by RyanMullins — APPROVED** [review]

File: test/scene-integration.test.ts (hunk 2 above)
Comment (jimbojw) [reply test/scene-integration.test.ts]: Done, and created issue #46 for additional consolidation.

File: src/lib/scene-internal.ts (hunk 1 above)
Comment (jimbojw) [reply src/lib/scene-internal.ts]: Thanks! I actually didn't know why it should be 2, but your explanation makes sense. Converted magic number to a constant with docs at the top.

**Review by RyanMullins — APPROVED** [review]
