### PR TITLE
Fix external border rendering and rename BorderRadiusWorld to BorderRadiusRelative

### LINKED ISSUE #52: Rename `BorderRadiusWorld` to `BorderRadiusRelative`
Contrary to its name, the `BorderRadiusWorld` sprite attribute sets a border radius proportional to the size of the sprite, not the underlying world coordinate system.

Rename `BorderRadiusWorld` to `BorderRadiusRelative` since that's what it actually implements. In the future, there may be a `BorderRadiusWorld`, but if so, it should have X and Y components since the scale has both of these components.

### LINKED ISSUE #54: Extend Sprite quad to accommodate border placed outside
The border of a Sprite may be placed inside or outside the edge of the Sprite. This is controlled by the `BorderPlacement` attribute. The default value of 0 places the border entirely within the edge. A value of 1 places the border entirely outside the edge. A value of 0.5 would straddle the edge.

Currently, the rendering of the sprite does not account for borders placed outside the edge. This means that border pixels beyond the strict bounding box of the sprite are not rendered. Screenshot:
Screen Shot 2022-09-20 at 11 45 19 AM

Instead, the bounds of the rendered quad should extend to cover borders beyond the sprite edge.

### PR DESCRIPTION
**Pull request by jimbojw**
- Fixes #54
- Fixes #52
- Adds tests for BorderPlacement=1 to assert correct rendering.
- Fixes glyph rendering to match above changes.
- Adds integration test for glyph rendering.

### CODE REVIEW

File: src/lib/shaders/scene-fragment-shader.ts [hunk 1]
```diff
@@ -294,9 +294,16 @@ float getDistRect() {
 
   // If the point of intrest is beyond the top corner, return the negative
   // distance to that corner.
-  if (all(greaterThan(p, ar))) {
+  bvec2 gt = greaterThan(p, ar);
```
Comment (jimbojw) [inline src/lib/shaders/scene-fragment-shader.ts:297]: This fixes a previously invisible bug, hidden by the clipping from bug #54.

File: test/scene-integration.test.ts [hunk 2]
```diff
@@ -560,11 +554,12 @@ describe('Scene', () => {
           const sprite = scene.createSprite();
           sprite.enter((s: SpriteView) => {
             s.BorderColorOpacity = .4;
+            s.BorderPlacement = 1;  // Place border outside shape.
```
Comment (jimbojw) [inline test/scene-integration.test.ts]: These changes ensure that the `hitTest()` succeeds only if the bounding box it tests includes an external border when specified.

**Comment by jimbojw** [comment]
There's one more thing I need to fix in this before merging. Didn't realize when I hit the "ready for review" button. The changes I made cause text to render larger than specified when there's a border placed outside the shape. I'll fix it then comment when it's ready for review.

File: src/lib/commands/setup-draw-command.ts [hunk 3]
```diff
@@ -88,12 +88,12 @@ export function setupDrawCommand(
...
+      // Corners of the rectangle, same for each sprite.
       'vertexCoordinates': [
-        [-0.5, -0.5, 0, 1],
-        [0.5, -0.5, 1, 1],
-        [-0.5, 0.5, 0, 0],
-        [0.5, 0.5, 1, 0],
+        [-0.5, -0.5],  // UV: [0, 1].
+        [0.5, -0.5],   // UV: [1, 1].
+        [-0.5, 0.5],   // UV: [0, 0].
+        [0.5, 0.5],    // UV: [1, 0].
```
Comment (jimbojw) [inline src/lib/commands/setup-draw-command.ts:96]: Previously, the UV coordinates of vertex corners were passed into the shaders. This worked as long as the vertex coordinates didn't move. However, with this PR, the vertex coordinates are pushed out by the vertex shader to make room for borders that extend beyond the shape boundary. Consequently, the UV coordinates must also be changed to match.

Now, rather than passing the UVs into the shaders, they are computed from the vertex coordinates by the fragment shader.

File: src/lib/glyph-mapper.ts [hunk 4]
```diff
@@ -61,11 +61,11 @@ export const DEFAULT_GLYPH_MAPPER_SETTINGS: GlyphMapperSettings =
     Object.freeze({
       maxTextureSize: 2048,
       fontSize: DEFAULT_GLYPH_FONT_SIZE_PX,
-      buffer: Math.ceil(DEFAULT_GLYPH_FONT_SIZE_PX / 4),
+      buffer: DEFAULT_GLYPH_FONT_SIZE_PX,
       radius: DEFAULT_GLYPH_FONT_SIZE_PX,
       // This default value ensures that a distance of zero coincides with the
       // edge of the glyph.
-      cutoff: 0.5,
+      cutoff: 1,
```
Comment (jimbojw) [inline src/lib/glyph-mapper.ts:68]: These changes to the default GlyphMapper settings simplify the logic in the fragment shader.

File: src/lib/shaders/scene-fragment-shader.ts [hunk 5]
```diff
@@ -313,10 +320,30 @@ float getDistRect() {
...
+  //   +------+       .      .
+  //
+  coordUv *= .5;
+  coordUv += .25;
+
+  // Offset into the texture according to the shapeTexture's location and size.
   vec2 textureUv =
       shapeTexture.xy +
-      shapeTexture.zw * varyingVertexCoordinates.zw;
-  return EDGE_DISTANCE_DILATION * texture2D(sdfTexture, textureUv).z - 1.;
```
Comment (jimbojw) [inline src/lib/shaders/scene-fragment-shader.ts:319]: The `EDGE_DISTANCE_DILATION` multiplication and `- 1.` are no longer needed as a consequence of the changes to the default GlyphMapper settings.

**Comment by jimbojw** [comment]
Update: This PR is now ready for review.

File: test/utils.ts [hunk 6]
```diff
@@ -0,0 +1,94 @@
...
+ * @fileoverview Utility functions used by tests.
+ */
+
+/**
+ * Create a <section> element inside the <article>.
+ */
+export function createSection(title: string): HTMLElement {
+  const section = document.createElement('section');
+  section.innerHTML = '<h2 class="title"></h2><div class="content"></div>';
+  section.querySelector('h2')!.textContent = title;
```
Comment (RyanMullins) [inline test/utils.ts]: You're probably going to run into a [`BANNED_PROPERTY_WRITE` error](https://github.com/google/closure-compiler/wiki/JS-Conformance-Framework#banned_property_write) for trying to [set `Element.prototype.innerHTML`](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/example_conformance_proto.textproto#L49) when you sync. Probably better to create these with `document.createElement()`, set their properties, and then append them to `section`.

File: test/scene-integration.test.ts (hunk 2 above)
Comment (RyanMullins) [reply test/scene-integration.test.ts]: Can you clarify that this means this test check that the `hitTest()` succeeds even if it only contains a sprite's boarder and not its fill?

File: test/glyph-integration.test.ts [hunk 7]
```diff
@@ -0,0 +1,168 @@
...
+  flex-direction: row;
+  flex-wrap: wrap;
+}
+.cw canvas {
+  background-image: linear-gradient(135deg, #aaa 50%, #ccc 50%);
+  background-size: 10px 10px;
+  box-shadow: inset 0 0 0 1px rgba(0,0,0,0.25);
+}
+</style>
+`;
```
Comment (RyanMullins) [inline test/glyph-integration.test.ts]: I think you'll run into a [BANNED_PROPERTY_WRITE error](https://github.com/google/closure-compiler/wiki/JS-Conformance-Framework#banned_property_write) when syncing this for [writing to `Element.prototype.innerHTML`](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/example_conformance_proto.textproto#L49). Probably best to use `document.createElement()` to create this `<style/>` element and set its `textContent`.

**Review by RyanMullins — APPROVED** [review]
Thanks for all the effort you put into comments in your shaders, it made the review process much easier.

**Comment by jimbojw** [comment]
Thanks for the review, I'll take care of these points.

File: test/glyph-integration.test.ts (hunk 7 above)
Comment (jimbojw) [reply test/glyph-integration.test.ts]: Moved to new `createArticle()` method in utils.

File: test/utils.ts (hunk 6 above)
Comment (jimbojw) [reply test/utils.ts]: Done.

File: test/scene-integration.test.ts (hunk 2 above)
Comment (jimbojw) [reply test/scene-integration.test.ts]: Done.
