### PR TITLE
Fix issue where exiting sprites are sometimes not removed

### LINKED ISSUE #77: Sprites sometimes continue to render after exit
Under some circumstances, Sprites that should have been removed after calling TextSelection's `bind()` method remain when they should have been removed from the Scene.

To reproduce:

- Run the text thrashing demo: `npm run text-demo`.
- Lower the `maxBatchTimeMs` value down to 1.
- Lower the `corpusPercentage` value down to 1.
- Zoom out and look down.

Expected: Only white text remains. Removed sprites (red) should have disappeared.

Actual: Red, removed sprites persist.

Screen Shot 2022-10-11 at 8 42 08 AM

Screenshot is from work-in-progress PR #75

### PR DESCRIPTION
**Pull request by jimbojw**
Fixes #77, #89

This change should have no visible effect on downstream code if `GeometricZoom` is unused and any of these conditions holds:

1. The downstream code never deletes sprites.
2. When the downstream code deletes a sprite, it sets the exiting sprite's opacity to 0 to fade out.
3. When the downstream code deletes a sprite, it sets the transition time to 0.

If downstream code doesn't meet these criteria, it means the code deletes a sprite, with a non-zero transition time, to a non-zero opacity. In such cases, occasionally the finishing of the transition will fall at just the wrong time to have the sprite continue to render. This is because its removal---flashing zeros to attributes before texture sync---is accidentally superseded.

This PR fixes the issue by adding an additional flag to the internal sprite properties called `zeroed` which tracks whether the sprite's attributes have been zeroed out. This flag is checked by the Texture sync task before calling `removeSprite()` to put the swatch back into rotation for another sprite.

This PR also introduces a gratuitous amount of unit testing. These tests will have to be significantly changed in response to the still-being-planned API update (see #83). So consider this test code to be short-lived.

UPDATE: This PR now also includes a fix to issue #89, in which non-zero values of `GeometricZoom` would cause sprites to have different sizes in logical pixels depending on the effective `devicePixelRatio`.

### CODE REVIEW

File: src/lib/tasks/run-callbacks.ts [hunk 1]
```diff
@@ -109,13 +109,8 @@ export function runCallbacks(
     // Append the current time to the arrival time value.
     spriteView.TransitionTimeMs += currentTimeMs;
 
-    // Make sure that the draw Ts range includes the current transition time
-    // plus a buffer to account for time taken by work tasks. Without the
-    // buffer, it can happen that the last drawn frame does not include the
-    // final resting state of the Sprite, especially when the user-specified
-    // transition time is near or below one frame (about 17ms).
-    coordinator.toDrawTsRange.expandToInclude(
-        spriteView.TransitionTimeMs + coordinator.workScheduler.maxWorkTimeMs);
```
Comment (jimbojw) [inline src/lib/tasks/run-callbacks.ts:118]: This solution only worked when `maxWorkTimeMs` was greater than or equal to the time between animation frames. Implementing constrained render tests revealed that this would not guarantee an additional draw call in all cases. Since this was not always effective, it's better to implement something that is.

Note the addition of `queueDraw()` to the Texture sync task. It is always the case that after a Texture sync, there needs to be a draw for the rendered pixels to show the changed values. Texture sync should always have queued a draw call, and now it does.

Before, with the hack solution above, we would get lucky that the added time happened to be long enough. Now, there will always be at least one more draw after a Texture sync.

File: src/lib/tasks/run-removal.ts [hunk 2]
```diff
@@ -85,22 +85,14 @@ export function runRemoval(
...
   let index = lowIndex;
 
   try {
     // Track number of steps to reduce calls to the remaining() callback.
     let step = 1;
 
     for (; index <= highIndex; index++) {
-      // Check to make sure we have made at least one step of progress and that
-      // we haven't run for too long without ceding the thread.
-      if (index > lowIndex && step++ % stepsBetweenChecks === 0 &&
```
Comment (jimbojw) [inline src/lib/tasks/run-removal.ts:99]: This time check was moved to the bottom of the loop to make it more clear that at least one pass of the loop will have completed before breaking due to time.

File: src/lib/tasks/run-removal.ts [hunk 3]
```diff
@@ -124,42 +116,47 @@ export function runRemoval(
...
       properties.lifecyclePhase = LifecyclePhase.NeedsTextureSync;
       coordinator.needsTextureSyncIndexRange.expandToInclude(properties.index);
+
+      // Break if we've run too long.
+      if (step++ % stepsBetweenChecks === 0 && remaining() <= 0) {
+        break;
+      }
     }
   } finally {
-    if (coordinator.needsTextureSyncIndexRange.isDefined) {
```
Comment (jimbojw) [inline src/lib/tasks/run-removal.ts:135]: This clause was moved below the for loop. Could be done in either order.

File: src/lib/tasks/run-removal.ts [hunk 4]
```diff
@@ -124,42 +116,47 @@ export function runRemoval(
...
-      coordinator.queueTextureSync();
-    }
+    // Expand the toBeRemovedIndexRange and toBeRemovedTsRange to include
+    // any sprites that were not visited due to time.
+    for (let i = index + 1; i <= highIndex; i++) {
+      const sprite = coordinator.sprites[i];
+      const properties = sprite[InternalPropertiesSymbol];
 
-    if (index < highIndex) {
```
Comment (jimbojw) [inline src/lib/tasks/run-removal.ts:139]: This block of code was overly complex. Simplified by the for loop.

File: karma.conf.ts [hunk 5]
```diff
@@ -27,7 +27,10 @@ module.exports = (config) => {
     frameworks: ['jasmine', 'webpack'],
 
     // List of files / patterns to load in the browser.
-    files: ['test/**/*.test.ts'],
+    files: [
+      // Set TEST_PATTERN env var to test a specific file.
+      process.env.TEST_PATTERN || 'test/**/*.test.ts',
```
Comment (jimbojw) [inline karma.conf.ts:32]: This makes it easy to run a specific test file from the command line without running the whole suite.

File: src/lib/tasks/run-removal.ts [hunk 6]
```diff
@@ -124,42 +116,48 @@ export function runRemoval(
         continue;
       }
 
-      // The sprite has been marked for removal, its in the right
+      // The sprite has been marked for removal, it's in the right
       // LifecyclePhase, and its time has expired. Flash zeros to the sprite's
       // data view and schedule it for a texture sync.
       properties.spriteView[DataViewSymbol].fill(0);
+      properties.zeroed = true;
```
Comment (jimbojw) [inline src/lib/tasks/run-removal.ts:129]: For #77, signals that a sprite that has been marked for removal has had its values flashed to zero.

File: src/lib/tasks/run-texture-sync.ts [hunk 7]
```diff
@@ -179,9 +180,10 @@ export function runTextureSync(coordinator: CoordinatorAPI): void {
     // The sprite was slated for removal. How to proceed depends on
     // whether it has more time left before its target arrival time.
 
-    if (properties.spriteView.TransitionTimeMs <= currentTimeMs) {
-      // The sprite was slated for removal, and its time has expired.
-      // Return its swatch for future reuse.
+    if (properties.zeroed &&
```
Comment (jimbojw) [inline src/lib/tasks/run-texture-sync.ts:183]: The other part of fixing #77. Only 'remove' the sprite if it has had its values zeroed out first. Without this clause, a sufficiently short exit transition state would never be visible, and instead the removed sprite's swatch would have the old dirty values still in it. This would cause the last known state of the sprite to continue rendering.

File: src/lib/tasks/run-texture-sync.ts [hunk 8]
```diff
@@ -217,4 +219,7 @@ export function runTextureSync(coordinator: CoordinatorAPI): void {
     height: rowHeight,
   };
   coordinator.targetValuesTexture.subimage(subimageData, 0, lowRow);
+
+  // After texture sync, we should always guarantee a draw call.
+  coordinator.queueDraw();
```
Comment (jimbojw) [inline src/lib/tasks/run-texture-sync.ts:224]: This is the more correct solution to ensuring that sprite's are always rendered in their updated state. Really, the Texture sync task should have always been queueing a draw.

In most cases, a draw would have already been queued. This line covers the rare case where a sprite's transition time is sufficiently short that it should have already arrived where it's going by the time the Texture sync is able to flash its values to the data texture.

File: test/constrained-selection-high-capacity.test.ts [hunk 9]
```diff
@@ -0,0 +1,336 @@
...
+
+  afterEach(() => {
+    scene[SceneInternalSymbol].regl.destroy();
+  });
+
+  it('should draw and remove a grid of sprites', async () => {
+    heading.textContent = 'grid of sprites';
+
+    // Draw (initial).
+    expect(workScheduler.taskIds).toEqual([DRAW_TASK_ID]);
```
Comment (jimbojw) [inline test/constrained-selection-high-capacity.test.ts:128]: Explicitly testing each task that's run by the WorkScheduler may be overkill. Minor changes to pipeline code will cause this kind of code to fail. But on the other hand, changes to the pipeline code ought to be infrequent. So having explicit, deep integration testing may be worth the price.

File: test/utils.ts [hunk 10]
```diff
@@ -109,13 +109,27 @@ export async function blobToImage(blob: Blob): Promise<HTMLImageElement> {
...
+ * @param pixelCount The number of pixels to produce.
+ * @param fillColor Array of four color channel values.
+ * @param convertOpacity Whether the fourth channel needs opacity-to-alpha
+ * conversion (multiply by 256).
  */
 export function filledColorArray(
     pixelCount: number,
-    fillColor: [number, number, number, number]): Uint8ClampedArray {
+    fillColor: number[],
+    convertOpacity = false,
```
Comment (jimbojw) [inline test/utils.ts:121]: Minor enhancement to make it easier to create filled color arrays for pixel-wise testing.

File: src/lib/tasks/run-removal.ts [hunk 11]
```diff
@@ -85,22 +85,14 @@ export function runRemoval(
...
-  // Keep track of the last index visited. This is outside of the try block so
-  // that we have access to it in the finally block afterwards.
+  // Define index outside of loop so we can access it in the finally clause.
   let index = lowIndex;
 
   try {
     // Track number of steps to reduce calls to the remaining() callback.
     let step = 1;
 
     for (; index <= highIndex; index++) {
```
Comment (RyanMullins) [inline src/lib/tasks/run-removal.ts]: nit: this seems like a good place for a `while`-loop instead of a `for`-loop given the funky syntax/lack of initialization clause.

File: src/lib/tasks/run-removal.ts [hunk 12]
```diff
@@ -124,42 +116,48 @@ export function runRemoval(
...
-              properties.spriteView.TransitionTimeMs);
-        }
+      // Ignore any sprites that are not both in the Rest phase and have had
+      // their 'toBeRemoved' property set (had an exit callback).
+      if (!properties.toBeRemoved ||
+          properties.lifecyclePhase !== LifecyclePhase.Rest) {
+        continue;
+      }
+
+      if (!properties.spriteView) {
```
Comment (RyanMullins) [inline src/lib/tasks/run-removal.ts]: nit: this is more of a personal style thing, but I have come to appreciate the specificity of `== null` checks rather than generic falsy evaluation, they help me distinguish between proper boolean value checks and existence checks.

**Review by RyanMullins — APPROVED** [review]

File: src/lib/tasks/run-removal.ts (hunk 12 above)
Comment (jimbojw) [reply src/lib/tasks/run-removal.ts]: Switched to explicit `undefined` check.

File: src/lib/tasks/run-removal.ts (hunk 11 above)
Comment (jimbojw) [reply src/lib/tasks/run-removal.ts]: Switched to `while` loop.

**Review by RyanMullins — APPROVED** [review]
